apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: demo
spec:
  refreshInterval: "10s" # Tự sync < 60s
  secretStoreRef:
    name: db-secret-store
    kind: SecretStore
  target:
    name: db-password-secret # K8s secret sẽ được tạo
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "/db/password"
