apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: db-secret-store
  namespace: demo
spec:
  provider:
    fake:
      data:
        - key: "/db/password"
          value: "mypassword123"
